Laboratorio_01/Controllers/ListNetJugController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laboratorio_01.Herramienta;
using Laboratorio_01.Models;
using System.IO;


namespace Laboratorio_01.Controllers
{
    public class ListNetJugController : Controller
    {
        // GET: ListNetJug
        public ActionResult InicioNet()
        {
            return View(CajaNet.Instance.JugadorListNet);
        }

  

        // GET: ListNetJug/Create
        public ActionResult Create()
        {
            return View("CreateListNet");
        }


        public ActionResult Busqueda(string Texto)
        {
            if (Texto == "Hello") { 
             return View("CreateListNet");
            }
            else
            {
                return View("Index");
            }
        }

        public ActionResult CargaArch(string Archivo)
        {
            try
            {
                string auxJug = "";
                StreamReader lector = new StreamReader(@Archivo);
                auxJug = lector.ReadLine();
                while ((auxJug = lector.ReadLine()) != null)
                {
                    Guardar_Jugadores_Lista(auxJug);
                }

                return View("InicioNet", CajaNet.Instance.JugadorListNet);
            }
            catch
            {
                return View("Error","Shared");
            }
        }

        public void Guardar_Jugadores_Lista(string linecomplete)
        {
           string[] data= linecomplete.Split(Convert.ToChar(";"));
            var Jugador = new mJugador
            {
                Club = data[0],
                Apellido = data[1],
                Name = data[2],
                Posicion = data[3],
                Salario = double.Parse(data[4]),
                Llave =  Convert.ToInt32(data[2][0]) * Convert.ToInt32(data[1][0]) *Convert.ToInt32(double.Parse(data[4]))
            };
            Jugador.Save();

        }


        // POST: ListNetJug/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                var Jugador = new mJugador
                {
                    Name = collection["Name"],
                    Apellido = collection["Apellido"],
                    Posicion = collection["Posicion"],
                    Salario = double.Parse(collection["Salario"]),
                    Club = collection["Club"],
                    Llave = Convert.ToInt32(collection["Name"][0]) * Convert.ToInt32(collection["Apellido"][0]) * Convert.ToInt32(double.Parse(collection["Salario"]))
                };
                if (Jugador.Save())
                {
                    return RedirectToAction("InicioNet");
                }
                else
                {
                    return View(Jugador);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: ListNetJug/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ListNetJug/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ListNetJug/Delete/5
     public ActionResult Delete(int id)
        {

            mJugador Jug = new mJugador();
            foreach (var item in CajaNet.Instance.JugadorListNet)
            {
                if(item.Llave==id)
                {
                    Jug = item;
                }
            }
            CajaNet.Instance.JugadorListNet.Remove(Jug);
            return View("InicioNet", CajaNet.Instance.JugadorListNet);
        }

        // POST: ListNetJug/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
           
                return RedirectToAction("InicioNet");
            }
            catch
            {
                return View("CreateLisNet");
            }
        }
    }
}

Laboratorio_01/Views/ListNetJug/CreateListNet.cshtml
@model Laboratorio_01.Models.mJugador

@{
    ViewBag.Title = "CreateListNet";
}

<h2>CreateListNet</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>mJugador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posicion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Club, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Club, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Club, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "InicioNet")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Laboratorio_01/Views/ListNetJug/InicioNet.cshtml
@model IEnumerable<Laboratorio_01.Models.mJugador>

@{
    ViewBag.Title = "InicioNet";
}

<h2>InicioNet</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div>
    @using(Html.BeginForm("Busqueda","ListNetJug"))
    {
       <label>Nombre</label>
       <input type="text" name="Texto"/>
       <button type="submit">Buscar</button>
    }
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Posicion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Club)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Posicion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Club)
        </td>
        <td>
     
            @* @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ })|*@
            @Html.ActionLink("Delete", "Delete", new { id=item.Llave })
        </td>
    </tr>
}



</table>

<div>
    @using (Html.BeginForm("CargaArch", "ListNetJug"))
    {<label>Carga de archivo</label>
        <input type="file" value="Hola" accept=".csv"  name="Archivo" />
        <button type="submit">Subir</button>
        }
    </div>